version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway_service
    ports:
      - '${GATEWAY_PORT:-3000}:3000'
    env_file:
      - ./apps/gateway/.env
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth_service:3001
      - EVENT_SERVICE_URL=http://event_service:3002
    volumes:
      - ./apps/gateway/src:/usr/src/app/apps/gateway/src
      - ./libs:/usr/src/app/libs
    depends_on:
      - auth_service
      - event_service
    networks:
      - event_net

  auth_service:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: auth_service_container
    ports:
      - '${AUTH_PORT:-3001}:3001'
    env_file:
      - ./apps/auth/.env
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://mongo_db:27017/auth_db
      - JWT_SECRET=YOUR_VERY_SECRET_KEY_AUTH
    volumes:
      - ./apps/auth/src:/usr/src/app/apps/auth/src
      - ./libs:/usr/src/app/libs
    depends_on:
      - mongo_db
    networks:
      - event_net

  event_service:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    container_name: event_service_container
    ports:
      - '${EVENT_PORT:-3002}:3002'
    env_file:
      - ./apps/event/.env
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://mongo_db:27017/event_db
      - JWT_SECRET=YOUR_VERY_SECRET_KEY_EVENT
    volumes:
      - ./apps/event/src:/usr/src/app/apps/event/src
      - ./libs:/usr/src/app/libs
    depends_on:
      - mongo_db
    networks:
      - event_net

  mongo_db:
    image: mongo:latest
    container_name: mongo_db_container
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - event_net

volumes:
  mongo_data:

networks:
  event_net:
    driver: bridge
